apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slpp.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slpp.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slpp.nodeServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slpp.labels" . | nindent 4 }}
